# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
gems:
    - jekyll-paginate
    - jekyll-gist

# Setup
title:            Suchin
tagline:          சச்சின் | ساشين | sʌʧɪn
description:      Graduate student at the University of Washington studying NLP.
url:              
baseurl:          https://kernelmachine.github.io/

author:
  name:           'Suchin'
  url:            https://twitter.com/ssgrn

paginate:         100

# Custom vars
github:
  repo:           https://github.com/kernelmachine

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
