# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               suchin
tagline:             writings
url:                 https://suchin.co
paginate:            1
baseurl:             ""
about:               "about"

# Gems
gems:
    - jekyll-paginate
    - jekyll-gist
# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Suchin Gururangan
  url:               https://suchin.co
  email:

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/pegasos1/pegasos1.github.io

markdown: kramdown
